Chore/websocket compressed payload
ls1intum/artemis-android pull request #197
Opened 2024-12-06 20:41 UTC by FelberMartin

### Problem Description
See #195 

### Changes
 

TODO

### Steps for testing

2025-01-16 16:55 UTC, eylulnc requested changes
There is a problem with message deleting, I compared it with the develop and it is working fine there.

When I tried to delete a message I got the pop up for - Could not delete the message.

2025-01-17 07:45 UTC, FelberMartin commented
> I had a some related to message deleting but could not reproduced it after the second build. When I tried to delete a message I got the pop up for - Could not delete the message.

Okay that's weird, these websocket changes should actually have no effect on the deletion of messages🤔. In case you find a way to reproduce the bug, please also try whether it occurs on `develop` aswell. 

I also tried reproducing the error but did not get an error pop up.

2025-01-23 15:37 UTC, julian-wls reviewed
I just tested the changes using TS1.
I experienced the following:
It worked for the first message and for the second message, the third message was not received, but the fourth was. For all other messages after that I always had to manually reload in order to fetch the message.

I checked the code, but I couldn't find a specific reason that could explain this behavior.

2025-01-27 09:54 UTC, FelberMartin commented
I do not think that the observed behaviours are related to this PR, I just tried to reproduce them again but it was able to observe the faulty behaviour. Additionally the compressed websocket payloads have not been enabled for the websocket topics affecting the native mobile apps yet. 

@julian-wls @eylulnc Would you mind trying to reproduce the faulty behaviours, and if they persist, also check whether they can also be observed on the `develop` branch? :)

2025-01-28 16:56 UTC, julian-wls approved these changes
I was not able to reproduce any of the issues I had before. My assumption is that the observed issues in my last review were related to network load. I also couldn't reproduce the issues on `develop`.
I don't think whatever the cause of this was is related to this PR.

Code lgtm.

2025-01-29 14:35 UTC, merged