Redesign notification settings
ls1intum/artemis-android pull request #206
Opened 2024-12-09 09:06 UTC by julian-wls

### Problem Description

### Changes
 

### Steps for testing

### Screenshots

2024-12-12 12:42 UTC, FelberMartin requested changes
Looking much better, thank you for taking care of this!

Two concerns:
1. If the user changes a setting and navigates back, the settings will not get synced with the server and the user probably does not know this. Maybe we should add a dialog in case the user has unsaved changes.
2. I tried changing and saving some settings, but I very often get an error dialog (I think only the first save did not show an error dialog for me). This is the logcat output: 
![image](https://github.com/user-attachments/assets/dd722483-f304-4f78-b892-e951bcc6a8de)

2024-12-12 12:42 UTC, FelberMartin commented on feature/push/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/push/ui/PushNotificationSettingCategoriesListUi.kt
> +                    .scale(0.9f)
Please introduce a constant for the scale value. This can then also be used in `PushNotificationSettingsUi`

2024-12-20 18:42 UTC, FelberMartin commented
I just noticed that it is currently possible to go to the Notification settings screen when the user is logged out, I assume this is not intended. Would you mind fixing this as part of this PR? @julian-wls 

I think it should be as easy as moving the `NotificationSection` into the `accountData?.let` statement in `SettingsScreen` :D

2025-01-04 13:40 UTC, julian-wls commented
> Looking much better, thank you for taking care of this!
> 
> Two concerns:
> 
> 1. If the user changes a setting and navigates back, the settings will not get synced with the server and the user probably does not know this. Maybe we should add a dialog in case the user has unsaved changes.
> 2. I tried changing and saving some settings, but I very often get an error dialog (I think only the first save did not show an error dialog for me). This is the logcat output:

1. I'll create a follow up PR tomorrow, which will probably include a dialog that warns a user when there are unsaved changes and has a button to save them.
2. I was not able to reproduce it. Correct me if I'm wrong:
       - I changed more than one switch
       - I clicked save
       - I did not receive an error in logcat

2025-01-04 16:34 UTC, FelberMartin approved these changes
Unfortunately I could also not reproduce the error consistently. But trying now I could only achieve it once, and by using the Network Inspector I saw that it was caused by a `500 Internal Server Error`, something about a duplicate key. However I missed to take a screenshot with the details and now I can not reproduce it anymore.

But anyways, as it is a server related error, this PR is good to merge :D

2025-01-04 19:37 UTC, eylulnc approved these changes
I also could not reproduce the already mentioned error log,  design looks good. 😊

2025-01-06 10:28 UTC, merged