`Communication`: Allow users to view sent attachments
ls1intum/artemis-android pull request #239
Opened 2024-12-18 18:39 UTC by julian-wls

### Problem Description

### Changes
 

### Steps for testing

### Screenshots

2024-12-21 13:24 UTC, FelberMartin requested changes
Looking very good overall, I think this is really a major improvement for the app. Good job! 😊 

Besides the code comments, I have a few general remarks:
1. When opening the pdf, it shows a page count of "Page 3/18", even though only the first 1,5 pages are visible. But I think you mentioned something about the page indicator behaving weirdly, so if there is no easy fix, its also fine if we leave it as is :)
2. The name of the pdf is currently just the timestamp (if think), could we change this to the name displayed in the markdown link? When I eg download the slides I cant really judge what the content of the file is by its name.
3. The action labelled with "Rotate PDF" felt quite counter-intuitive for me, from this name I would have expected the pdfs to rotate 90°. But I also can't find a short, better fitting alternative. Its a little bit longer than the other labels, but maybe "Toggle View Mode" would be a better fit, what do you think @julian-wls ?
4. Somewhere in the code zoom is mentioned, I tried to zoom the pdfs by pinching with two fingers in the bottomSheet, but nothing happened. Is this intended?

![image](https://github.com/user-attachments/assets/98734a0b-0761-448e-afe6-57adbdbf52b5)

2024-12-21 15:49 UTC, julian-wls commented on core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/markdown/link_resolving/MarkdownLinkResolverImpl.kt
> +                customTabsIntent.launchUrl(context, Uri.parse(link))
Oh true, I totally forgot that.

2024-12-21 15:50 UTC, julian-wls commented on core/ui/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/core/ui/markdown/link_resolving/MarkdownLinkResolverImpl.kt
> +        val (bottomSheetState, setBottomSheetState) = remember { mutableStateOf(LinkBottomSheetState.WEBVIEWSTATE) }
The main reason was, that I had a hard time debugging it at some point, cause the code was not quite readable before. That's the reason I changed it to this syntax.

2024-12-21 15:57 UTC, julian-wls commented
> * When opening the pdf, it shows a page count of "Page 3/18", even though only the first 1,5 pages are visible. But I think you mentioned something about the page indicator behaving weirdly, so if there is no easy fix, its also fine if we leave it as is :)
> * The name of the pdf is currently just the timestamp (if think), could we change this to the name displayed in the markdown link? When I eg download the slides I cant really judge what the content of the file is by its name.
> * The action labelled with "Rotate PDF" felt quite counter-intuitive for me, from this name I would have expected the pdfs to rotate 90°. But I also can't find a short, better fitting alternative. Its a little bit longer than the other labels, but maybe "Toggle View Mode" would be a better fit, what do you think @julian-wls ?
> * Somewhere in the code zoom is mentioned, I tried to zoom the pdfs by pinching with two fingers in the bottomSheet, but nothing happened. Is this intended?

Thanks for reviewing. I really appreciate the feedback :)

Here are the answers:
1. It actually shows three pages when you open the entire modal bottom sheet. There is a function in VerticalPdfReaderState, which determines how many pages are shown and sets the current page to the last page that is currently open. If we change this the last page of the pdf would never be reached.
2. I thought about this too, but I didn't find any way to access the string in the markdown text (I think that would be the only way to get the name). The Link resolver only checks when a link has been clicked and only returns the link, not the title.
3. I think you're right. Toggle view mode sounds good to me. Would you still keep this icon, though? @FelberMartin 
4. For zooming you have to double tap the page, first.

2024-12-22 15:23 UTC, eylulnc commented
Thanks for the great work! This is indeed a huge improvement 😊

I checked it out based on our previous discussions and have a few observations:
**Page Indicator:** Regarding the ‘Page 3/18’ indicator, I didn’t encounter this issue during my testing—it seems to be working fine for me.
**Bottom Sheet Behavior:** I really like the toast—it’s a nice touch! However, I’d prefer not to see an empty bottom sheet when there’s an error (e.g., no internet connection), as it feels a bit disconnected.

<img width="200" alt="Screenshot 2024-12-22 at 15 58 38" src="https://github.com/user-attachments/assets/7622dc02-49ff-4477-b49c-9bf12d591379" />

Additionally, I noticed the bottom sheet expands into the unsafe zone—perhaps adding some padding at the top could make it look better. What do you think?

**Naming:**  I agree it would be nice to have more meaningful names for downloaded files. However, if this isn’t feasible, it’s fine as is.

<img width="200" alt="Screenshot 2024-12-22 at 16 00 05" src="https://github.com/user-attachments/assets/161b0408-bbcf-458e-b3b0-13a03d969c28" />

**Rotation Action:** Initially, I found the label “Rotate PDF” a bit confusing because I expected it to change the PDF’s orientation. Since it toggles between scroll and swipe modes, maybe a label like “Read Mode” could help clarify this. Keeping the current icon is fine, but if you feel the label doesn’t cause confusion, I think it’s okay to keep it as is.

2024-12-27 17:29 UTC, FelberMartin approved these changes
Lgtm now! 

Regarding the naming of the "Rotate" item, I thinks its worth to take the bigger dialog to avoid the confusing naming of "Rotate pdf". Keeping the icon seems fine to me

2025-01-04 10:42 UTC, FelberMartin commented
> Bottom Sheet Behavior: I really like the toast—it’s a nice touch! However, I’d prefer not to see an empty bottom sheet when there’s an error (e.g., no internet connection), as it feels a bit disconnected.

@julian-wls did you consider this comment by Eylül?

2025-01-04 12:02 UTC, julian-wls commented
> > Bottom Sheet Behavior: I really like the toast—it’s a nice touch! However, I’d prefer not to see an empty bottom sheet when there’s an error (e.g., no internet connection), as it feels a bit disconnected.
> 
> @julian-wls did you consider this comment by Eylül?

Sorry I overlooked it, thanks for the hint. I added a change that allows closing the bottom sheet in case an error occurred and added padding to the top.

2025-01-04 12:50 UTC, merged