`Feature`: Change to Bottom navigation bar
ls1intum/artemis-android pull request #246
Opened 2024-12-20 19:24 UTC by FelberMartin

### Problem Description

### Changes
 

### Steps for testing

### Screenshots

2025-01-25 11:25 UTC, eylulnc requested changes
This is looking really good! I am always a bottom navigation person so 😍.
I have few small points.
1 - In the tablet view test area is really close to the bottom-nav-menu. Maybe padding can be add?
<img width="438" alt="Screenshot 2025-01-25 at 12 17 47" src="https://github.com/user-attachments/assets/c5675795-163d-4ce5-8783-861d57101c29" />

2 - In the conversation disabled case, We navigate and saw in very dark background, communication disabled message.
<img width="250" alt="Screenshot 2025-01-25 at 12 21 51" src="https://github.com/user-attachments/assets/776abaf7-6c28-4f49-ac7f-ecccb84bea62" />

In iOS they just do not show the tab, but I prefer to see the tab instead of having to only 2 tab on the bottom, maybe we can stay in the same navigation level and background so that message is more visible as in the early version. What do you think?

<img width="250" alt="Screenshot 2025-01-25 at 12 24 26" src="https://github.com/user-attachments/assets/824b4054-b314-456d-beb4-c4f05b7b827d" />

2025-01-26 14:10 UTC, FelberMartin commented
>  1 - In the tablet view test area is really close to the bottom-nav-menu. Maybe padding can be add?

I will add a small padding for now, but I assume we would probably have to undo the padding in Julians ReplyTextField refactoring PR #320. I will keep in mind to check this before merging the later of these two PRs :)

> 2 - In the conversation disabled case, We navigate and saw in very dark background, communication disabled message.

Good catch, this was just because I missed to use the scaffold in the case where communication is disabled. The CommunicatinDisabledInfo now shows as in the previous versions again :D 

![image](https://github.com/user-attachments/assets/108ddd97-be9a-40a9-917f-f85ac252d6d3)

2025-01-28 10:09 UTC, FelberMartin commented
FYI: Due to the recent merge of #320, the padding of the ReplyTextField is off now. I will have a look today

2025-01-29 09:16 UTC, julian-wls reviewed
Really nice change, this makes navigation a lot better!

Only thing I noticed while testing is that the BasicDataStateUi is not visible in the ConversationOverview when using pull to refresh, instead the screen becomes black:

https://github.com/user-attachments/assets/2aa725eb-5695-4085-825c-e8d6ca58af4e

Couldn't find issues in the code.

2025-01-29 14:49 UTC, merged