`Feature`: Add Unordered and Ordered List Options to Formats
ls1intum/artemis-android pull request #253
Opened 2024-12-22 20:51 UTC by eylulnc

### Problem Description
Our mobile markdown editor lacked support for creating ordered or unordered lists, a feature already available in the web editor. Mobile users were unable to format lists conveniently, requiring them to manually type prefixes like -  or 1. , which disrupted the ease of composing structured messages.

### Changes
 
**Ordered List:** Adds logic to insert a 1.  prefix (or increment an existing number, e.g. 2.  -> 3. ) when the user selects “Ordered List.”

**Unordered List:** Adds logic to insert a -  prefix.

**Formatting Dropdown:** Introduces a single “List” icon in the toolbar. Tapping it reveals a dropdown to choose between unordered/ordered lists.

### Steps for testing
1.	Open any conversation
2.	Tap the “List” icon. Verify a dropdown appears with “Unordered List” and “Ordered List.”
3.	Choose “Unordered List” to insert or apply -  at the cursor.
4.	Choose “Ordered List” to insert or apply 1.  (or increment an existing number).
6.	Check auto-continuation: If a line starts with -  or N. , pressing Enter automatically inserts another bullet or the next number.

### Screenshots

https://github.com/user-attachments/assets/8a8cc416-2607-4588-93d5-1fb6d637204b

<img width="250" alt="Screenshot 2024-12-22 at 21 31 05" src="https://github.com/user-attachments/assets/89516545-325e-442b-84ae-747e305388c1" />

2024-12-27 18:01 UTC, FelberMartin requested changes
Very nice, I like this enhancement!

I have a few minor notes I noticed during testing:
1. When clicking the list icon, the keyboard is collapsed. Would be nice if we could prevent this from happening, but tbh I am not sure whether / how this is possible.
2. From the implementation of the `continueList` function I take that the list autocompletion should also work when the cursor is not at the end of the text. But during testing, this scenario did not work. I think this may be related to the check in line 823. 
3. This is not directly related to this PRs scope, but if it is not too much effort, we could also include this here: When I switch from "Edit" to "Preview" mode, the formatting options are still shown. I think these should be hidden in this context. But if there is no easy fix, we can create a separate issue for this :D 

![ArtemisMarkdownListAutocompletion](https://github.com/user-attachments/assets/cf7900ef-d115-498a-bec3-54a25a4390ed)

2025-01-03 20:22 UTC, FelberMartin requested changes
Nice, points 2. and 3. of my previous review are fixed now :D

Did you take a look at 1.? When I checked this issue persisted

2025-01-03 20:22 UTC, FelberMartin commented on feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/reply/ReplyTextField.kt
> +    val afterUnordered = continueUnorderedList(oldText, newValue)
I'm thinking, maybe we should move this whole list continuation logic out of this file into a `MarkdownListContinuationUtil` file. This would allow us to write some basic unit tests to ensure the proper behaviour and also avoid bloating the `ReplyTextField.kt` file

2025-01-04 19:15 UTC, eylulnc commented on feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/reply/ReplyTextField.kt
> +    val afterUnordered = continueUnorderedList(oldText, newValue)
I will take a look at this and for the !.st point I could not find any solution

2025-01-09 09:36 UTC, FelberMartin requested changes
Some minor changes :)

2025-01-09 09:36 UTC, FelberMartin commented on feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/reply/MarkdownListContinuationUtil.kt
> +fun continueListIfApplicable(
Please wrap the methods in this file in a `object MarkdownListcontinuationUtil`, so that the call to the util functions is more explicit. I think you can also mark all methods besides the called one as private

2025-01-09 09:36 UTC, FelberMartin commented on feature/metis/conversation/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/reply/MarkdownListContinuationUtilTest.kt
> +    }
Please add a test to cover list continuation when the cursor is not at the end of the text (to cover the scenario of point 2. of my previous change request)

2025-01-09 09:36 UTC, FelberMartin commented on feature/metis/conversation/src/test/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/reply/MarkdownListContinuationUtilTest.kt
> +@RunWith(AndroidJUnit4::class)
Use `@RunWith(RobolectricTestRunner::class)` instead, as we do not need Android specific behaviour for this test.

2025-01-09 09:36 UTC, FelberMartin commented on feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/reply/ReplyTextField.kt
> +                        if (displayTextField || currentTextFieldValue.text.isNotBlank()) {
Did you check whether this if statement is required?

2025-01-14 13:16 UTC, eylulnc commented on feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/reply/ReplyTextField.kt
> +                        if (displayTextField || currentTextFieldValue.text.isNotBlank()) {
I believe this was supposed to make the formatting options visible only in edit mode, but it didn’t work as expected. I removed it and tested again but didn’t notice any difference in behavior.

2025-01-14 13:33 UTC, eylulnc commented
> Nice, points 2. and 3. of my previous review are fixed now :D
> 
> Did you take a look at 1.? When I checked this issue persisted

1. should be fixed. Can you verify?

2025-01-16 09:21 UTC, FelberMartin approved these changes
Can confirm, pressing the listing formatting option does no longer collapse the keyboard, this is awesome :D

Ready to merge from my side

2025-01-16 11:30 UTC, julian-wls approved these changes
Tested it and works as expected.
Code lgtm.

2025-01-16 12:55 UTC, merged