`Feature`: Save messages for later
ls1intum/artemis-android pull request #259
Opened 2024-12-30 10:40 UTC by FelberMartin

### Problem Description

### Changes
 

### Steps for testing

### Screenshots

2025-01-16 12:24 UTC, julian-wls requested changes
Looks really nice and works as expected. 

Regarding the flickering of the PostActionBar: I also noticed that after the reload the isSaved Button is sometimes not correctly updated, but I wa not able to constantly reproduce this.
I also noticed some padding issues, see below:

2025-01-16 12:24 UTC, julian-wls commented on feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/SavedPostsScreen.kt
> +                    modifier = Modifier.fillMaxSize(),
Please add `.padding(horizontal = 8.dp)` here or on the BasicDataStateUi

2025-01-16 12:24 UTC, julian-wls commented on feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/SavedPostsScreen.kt
> +            modifier = modifier.padding(paddingValues)
Please apply the padding only to the top here and add `consumeWindowInsets(WindowInsets.systemBars)`

2025-01-16 12:24 UTC, julian-wls commented on feature/metis/conversation/src/main/kotlin/de/tum/informatics/www1/artemis/native_app/feature/metis/conversation/ui/SavedPostsScreen.kt
> +                    modifier = Modifier.padding(bottom = 8.dp),
Please change this to .padding(start = 8.dp, bottom = 8.dp, end = 8.dp) here

2025-01-16 14:20 UTC, FelberMartin commented
I added the paddings as requested. While debugging the padding I found that there are some issues with the padding propagated by the CourseScreenUI, but I will create a follow up PR about this, this PR is already way to huge :D

Regarding the inconsistent icon in the PostActionBar I was not able to reproduce it. In case you find out how, let me know :)

2025-01-16 16:44 UTC, eylulnc approved these changes
Looking really nice! One point for discussion: what do you think about placing the button in 'In Progress' inside the text area (I dont know if its possible though😅), aligned to the right, or using icon buttons like on the web? Just a thought to improve UI but not a must 😅

2025-01-17 07:34 UTC, FelberMartin commented
> One point for discussion: what do you think about placing the button in 'In Progress' inside the text area (I dont know if its possible though😅), aligned to the right, or using icon buttons like on the web? Just a thought to improve UI but not a must 😅

It is somehow possible, we can not directly put the button inside the textarea, but next to or below it. That's what it would look like with the button inside the card:

![image](https://github.com/user-attachments/assets/69573816-54d1-4ef1-9ff2-041665c7637f)

Compared to previous:
![image](https://github.com/user-attachments/assets/08203bf0-7689-48a2-bf94-9a20a49de745)

Let me know what you think @eylulnc  :D

2025-01-18 17:55 UTC, eylulnc commented
> > One point for discussion: what do you think about placing the button in 'In Progress' inside the text area (I dont know if its possible though😅), aligned to the right, or using icon buttons like on the web? Just a thought to improve UI but not a must 😅
> 
> It is somehow possible, we can not directly put the button inside the textarea, but next to or below it. That's what it would look like with the button inside the card:
> 
> ![image](https://private-user-images.githubusercontent.com/45291671/404197825-69573816-54d1-4ef1-9ff2-041665c7637f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcyMjMxNDAsIm5iZiI6MTczNzIyMjg0MCwicGF0aCI6Ii80NTI5MTY3MS80MDQxOTc4MjUtNjk1NzM4MTYtNTRkMS00ZWYxLTlmZjItMDQxNjY1Yzc2MzdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE4VDE3NTQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwNTgyZjZiMjUyMGI5ZjliOGY2YzNiOGM0NDU0NmVhMzgxOTI0NzdjNGU1MWZlMGM1YjhhM2ZiNDYxMzkyZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vvMw7cZAXU3SMRqWFyHnizH941_9dLYwN23Bo2s7DG4)
> 
> Compared to previous: ![image](https://private-user-images.githubusercontent.com/45291671/404194613-08203bf0-7689-48a2-bf94-9a20a49de745.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcyMjMxNDAsIm5iZiI6MTczNzIyMjg0MCwicGF0aCI6Ii80NTI5MTY3MS80MDQxOTQ2MTMtMDgyMDNiZjAtNzY4OS00OGEyLWJmOTQtOWEyMGE0OWRlNzQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE4VDE3NTQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1ODQ4ZWE1MGFhYmE2NjEwNTNkYmRiM2ZjYTY4OTQ5YjQ5MzhjMmQ0ZGQwN2IwNmU1MDcwODE3YjE1NzFjZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PT6SiSS2rP0CYoZpc-6qphwNsolL5JKfnPUdvmPVc6Y)
> 
> Let me know what you think @eylulnc :D

I really like the new one, I think it looks more appealing 😊

2025-01-22 17:29 UTC, julian-wls approved these changes
Code lgtm now,
I agree with @eylulnc. The new design with the button inside the list item looks better.
I also tested the changes once again in detail and couldn't find any issues. This branch can be merged imo.

2025-01-23 09:03 UTC, merged